version: "3"

networks:
  madonna:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: madonna-nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - madonna

  mysql:
    image: mysql:5.7.22
    container_name: madonna-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: madonna
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - madonna


  mailhog_server:
    image: mailhog/mailhog
    container_name: madonna-mailhog
    #this is optional
    tty: true
    ports:
      - '1025:1025'
      - '8025:8025'
    #this is optional
    #restart: always
    restart: on-failure
    #set the same network as the other services
    networks:
      - madonna

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: madonna-phpmyadmin
    depends_on:
      - mysql
    external_links:
      - mysql:db
    ports:
      - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
    networks:
      - madonna

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madonna-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9009:9000"
    networks:
      - madonna

#Volumes
volumes:
  mysql:
    driver: local


